In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv("data/raw/Air_quality.csv")
df1

,indicator_data_id,indicator_id,name,Measure,geo_type_name,geo_entity_id,geo_entity_name,year_description,data_valuemessage
0,130728,646,Air Toxics Concentrations- Average Benzene Con...,Average Concentration,Borough,1,Bronx,2005,2.8
1,130729,646,Air Toxics Concentrations- Average Benzene Con...,Average Concentration,Borough,2,Brooklyn,2005,2.8
2,130730,646,Air Toxics Concentrations- Average Benzene Con...,Average Concentration,Borough,3,Manhattan,2005,4.7
3,130731,646,Air Toxics Concentrations- Average Benzene Con...,Average Concentration,Borough,4,Queens,2005,1.9
4,130732,646,Air Toxics Concentrations- Average Benzene Con...,Average Concentration,Borough,5,Staten Island,2005,1.6
...,...,...,...,...,...,...,...,...,...
2764,151756,645,Traffic Density- Annual Vehicle Miles Traveled...,Per 100 km2,UHF42,410,Rockaways,2005,0.2
2765,151757,645,Traffic Density- Annual Vehicle Miles Traveled...,Per 100 km2,UHF42,501,Port Richmond,2005,0.3
2766,151758,645,Traffic Density- Annual Vehicle Miles Traveled...,Per 100 km2,UHF42,502,Stapleton - St. George,2005,0.8
2767,151759,645,Traffic Density- Annual Vehicle Miles Traveled...,Per 100 km2,UHF42,503,Willowbrook,2005,0.8
2768,151760,645,Traffic Density- Annual Vehicle Miles Traveled...,Per 100 km2,UHF42,504,South Beach - Tottenville,2005,0.3